[workspace]
members = [
    "utils",
    "day_1_1",
    "day_1_2",
    "day_2_1",
    "day_2_2",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
utils = { path = "utils" }
eyre = "0.6.5"

